apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "anyway-backend"
  namespace: "default"
  labels:
    app: "anyway-backend"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "anyway-backend"
  template:
    metadata:
      labels:
        app: "anyway-backend"
    spec:
      containers:
      - name: "anyway-backend"
        image: eu.gcr.io/anyway-backend/anyway-backend:lstest
        imagePullPolicy: Always
      restartPolicy: Always


---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "anyway-backend-service"
  namespace: "default"
  labels:
    app: "anyway-backend"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  selector:
    app: "anyway-backend"
  type: "LoadBalancer"

---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "postgres-config"
  namespace: "default"
  labels:
    app: "postgres"
data:
  POSTGRES_DB: "anyway"
  POSTGRES_USER: "anyway"
  POSTGRES_PASSWORD: "anyway"


---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "anyway-backend-db"
  namespace: "default"
  labels:
    app: "anyway-backend-db"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "anyway-backend-db"
  template:
    metadata:
      labels:
        app: "anyway-backend-db"
    spec:
      containers:
      - name: "anyway-backend-db"
        image: eu.gcr.io/anyway-backend/anyway-backend-db:latest
        imagePullPolicy: Always
        env:
        - name: "POSTGRES_DB"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_DB"
              name: "postgres-config"
        - name: "POSTGRES_USER"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_USER"
              name: "postgres-config"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "POSTGRES_PASSWORD"
              name: "postgres-config"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data-pv-claim
      restartPolicy: Always

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: anyway-backend-db-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 5432
  selector:
    app: anyway-backend-db-service
  type: LoadBalancer
