version: '3.7'

services:
  anyway:
    image: ${ANYWAY_BACKEND_IMG}
    build:
        context: .
        args:
          - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/anyway
    restart: always
    depends_on:
      - db

  db:
    image: ${ANYWAY_BACKEND_DB_IMG}
    build: db_docker
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data 
    restart: always
    
  migration:
    image: ${ANYWAY_BACKEND_IMG}
    command: ["bash", "./wait-for-postgres.sh", "db","alembic", "upgrade", "head"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # - ANYWAY_BACKEND_DB_IMG=${ANYWAY_BACKEND_DB_IMG}
    depends_on:
      - db
    # volumes:
       # - /var/run/docker.sock:/var/run/docker.sock
       # - /usr/bin/docker:/usr/bin/docker
    
volumes: 
  db_data:
